version: "3.8"
services:
  app:
    image: fastapi_pg_async_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PSQL__HOST: postgres
      PSQL__USER: postgres
      PSQL__PASSWORD: psqldevpass
      PSQL__DB: postgres
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:14-alpine
    volumes:
      - fastapi-psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: psqldevpass

volumes:
  fastapi-psql-data:
